version: '3.8'
 
services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - target:/workspace/target
    command: sleep infinity
    
volumes:
  target:
  node_modules: