version: '3.8'

volumes:
  postgres-data:
  target:
  node_modules:
 
services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        # dont forget to cp .env.example to .env
        - .env
    volumes:
      - ..:/workspace:cached
      # Give access to ssh keys on the host
      - ~/.ssh:/home/host-ssh:cached
      # We need this so docker in docker works
      - /var/run/docker.sock:/var/run/docker.sock
      - target:/workspace/target # Set target as a volume for performance. 
      # Uncomment the next line to improve performance when using node.
      #- node_modules:/workspace/crates/front-end/node_modules 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    